version: "3.7"
services:
  jazeel:
    container_name: grana
    # image: j2_middleware:$CDT_IMAGE_VERSION
    image: grana:1.0
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      labels:
        com.vf.maintainer: "Virtual Force"
        # com.jazeel.version: $CDT_IMAGE_VERSION
        com.vf.description: "Container for boiler plate"
    command: npm run start
    networks:
      - grana
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
networks:
  grana:
    name: grana
